"""initial migration

Revision ID: ee2cb5d8915a
Revises: None
Create Date: 2016-03-02 13:55:25.021355

"""

# revision identifiers, used by Alembic.
revision = 'ee2cb5d8915a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('ballot_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
